/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bottom_bar: typeof import('./src/components/bottom_bar/index.vue')['default']
    Carousel: typeof import('./src/components/carousel/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    Hospital: typeof import('./src/components/hospital/index.vue')['default']
    HospitalCard: typeof import('./src/components/hospital-card/index.vue')['default']
    HospitalSearch: typeof import('./src/components/hospital-search/index.vue')['default']
    Level: typeof import('./src/components/level/index.vue')['default']
    Region: typeof import('./src/components/region/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/index.vue')['default']
    Top_bar: typeof import('./src/components/top_bar/index.vue')['default']
  }
}
